### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by ogguraaaaa** [ogguraaaaa/furima-36552#22]
・自身のフリマアプリのURL
https://furima-36552.herokuapp.com/

・Basic認証のIDとパスワード
ユーザー名　→ admin
パスワード　→ 2222

・出品者用のメールアドレスとパスワード
div@div.com
div111

・購入者用のメールアドレスとパスワード
ttt@ttt.com
ttt111

**Comment by mo1015** [comment]
ご提出ありがとうございます！
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]

- [ ] **商品が出品されていない状態では、ダミーの商品情報が表示されるようにしましょう**
今回商品が出品された状態で提出いただいたため、上記項目の確認ができませんでした。データベースをリセットして再提出いただくようお願いいたします。

- [ ] **出品ページにて、発送までの日数は、「---、1\~2日で発送、2\~3日で発送、4\~7日で発送」の4項目が表示されるようにしましょう（--- は初期値として設定すること）**
異なる日数が表示されています。
<img width="359" alt="スクリーンショット 2021-09-15 12 58 46" src="https://user-images.githubusercontent.com/62644781/133368455-29817c04-19ef-4dc9-b546-6f43959eefa9.png">


- [ ] **電話番号は、10桁以上11桁以内の半角数値のみ保存可能としましょう**
9桁以内で入力しても購入できてしまいます。

修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by mo1015** [comment]
フリマアプリ達成要件分の開発お疲れ様でした！
正常に動作することが確認できました！LGTMです！　
おめでとうございます🎉


**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願いいたします。**
**※Github上の最終課題の履歴はここまで頑張ってきた証です。削除せず大切に保管するようにしましょう。**

ここまで培ってきた知識や学びを活かして、これからは下記例のようなさらなる学習に取り組みましょう！

＜今後の学習例＞
・フリマアプリ追加実装
・オリジナルアプリ開発
・今まで学んできた言語あるいは新言語の学習　等
今後の学習方針や学習計画については、担当ライフコーチまでお気軽にご相談くださいませ。
また、以下提出物に関するリマインドです。

＜提出物＞
・最終課題説明文（フリマアプリ達成要件および、追加実装内容にて作成をお願いいたします）
・要件定義（追加実装あるいは、オリジナルアプリの内容で作成をお願いいたします）
※提出期日については、最終課題開始時に配布した下記動画にてご確認いただきますようお願いいたします。

＜最終課題に関する締め切りについての動画＞
https://master.tech-camp.in/v2/curriculums/6852

今後の流れに関して、もしご不明点がございましたら、
担当ライフコーチまでお気兼ねなくお申し付けくださいませ。
![最終課題終了_おめでとう画像2](https://user-images.githubusercontent.com/62644781/133377350-427af5fd-f6c3-491c-97a5-99dc0af9d944.png)
